### PR TITLE
protocol: remove legacy hash functions RIPEMD-160 and SHA1

### PR DESCRIPTION
**Pull request by oleganza**
These hash functions are unnecessary, outdated, and (in the case of SHA1, anyway) weak.

This is a part of a package of breaking changes in P1: #239

### CODE REVIEW

**Comment by kr** [comment]
LGTM

**Comment by oleganza** [comment]
@kr @danrobinson PTAL. Implementation is updated with RIPEMD160 and SHA1 removed.

WARNING: this is a hard-forking change to the protocol.

**Comment by kr** [comment]
:eyes:

**Comment by kr** [comment]
LGTM (we should also probably follow up by removing directory vendor/golang.org/x/crypto/ripemd160).

**Comment by oleganza** [comment]
@kr I removed `ripemd160` package in this PR for completeness.

**Pull request merged**
