### PR TITLE
core: cache account and asset aliases

### PR DESCRIPTION
**Pull request by jbowens**
Filtering aliases is the source of > 50% of all SQL queries in one of my
benchmarks.

### CODE REVIEW

**Comment by jbowens** [comment]
PTAL

**Comment by bobg** [comment]
:eyes:

**Comment by bobg** [comment]
This looks LGTM but if filtering aliases is as common as you say, it is probably worth trying to combine the alias->id lookup with reading of the actual account or asset data via a join (in addition to caching), to avoid a separate db roundtrip. Maybe give that a try?

**Comment by jbowens** [comment]
> This looks LGTM but if filtering aliases is as common as you say, it is probably worth trying to combine the alias->id lookup with reading of the actual account or asset data via a join (in addition to caching), to avoid a separate db roundtrip. Maybe give that a try?

Since we already have caching of asset id -> asset data, I'm not too worried about it. We can follow up if it's a problem.

**Pull request merged**
