### PR TITLE
core: tick version to 1.1.4

### PR DESCRIPTION
**Pull request by dominic**

### CODE REVIEW

**Comment by dominic** [comment]
This update will include the following commits:

- https://github.com/chain/chain/commit/7b153b849cc22816563aeefae282a482116d746f
- https://github.com/chain/chain/commit/57dc0992887b2a6307b04963154091df2f42d8ab
- https://github.com/chain/chain/commit/1eb9fffcc5a90a2e1bb5e3ef74b0b0902adeb336

**Comment by kr** [comment]
Changelog should also include a description of the cored bugfix from 7b153b849cc22816563aeefae282a482116d746f. Something like

> - fix a bug that could cause some annotated transaction fields to be missing under high load

**Comment by dominic** [comment]
@kr updated - PTL again

**Comment by kr** [comment]
LGTM

**Pull request merged**
