### PR TITLE
sdk/java: allow customizable CA certs

### PR DESCRIPTION
**Pull request by jeffomatic**
This is an interface revision of #687. It should be backported to the `1.1-stable` branch.

### CODE REVIEW

**Comment by jeffomatic** [comment]
PTAL. Usage example:

```
    String pem = new String(Files.readAllBytes(Paths.get("./certs.pem")));
    Client client = new Client.Builder()
      .setURL("https://localhost:8443")
      .setTrustedCerts(pem)
      .build();
```

**Comment by kr** [comment]
Should we read the file for them? Take a filepath as the parameter?

**Comment by jeffomatic** [comment]
I generally prefer being agnostic to the source of the certs, e.g. they could be sitting in an envvar too. Might be convenient to add a file-based option though? `setTrustedCertsFromFile`?

**Comment by ryandotsmith** [comment]
@jeffomatic +1 for reading from a file. I think we are moving this direction for cored config.

**Comment by jeffomatic** [comment]
ok

**Comment by jeffomatic** [comment]
@kr @ryandotsmith revised to read from file, PTAL

cf: https://github.com/chain/chain/pull/688/commits/e7ef31f109bfc821017d3e2ba04865b998a26b45

**Pull request merged**
