### PR TITLE
protocol/bc: create AssetDefinition type, ComputeAssetID is its hash

### PR DESCRIPTION
**Pull request by bobg**
The spec revision in https://github.com/chain/chain/pull/728 specifies a new Asset Definition type. This change reflects that.

This is a carved-off piece of https://github.com/chain/chain/pull/788

### CODE REVIEW

**Comment by bobg** [comment]
PTAL

**Comment by jbowens** [comment]
Most of this PR seems to be propagating errors from `writeForHash`. Do we ever use `writeForHash` with a writer that's not a buffer? Besides `io.Writer` errors, it looks like the only other errors are reflection type errors.

Can we modify the `writeForHash` or `ComputeAssetID` interface to panic instead?

**Comment by bobg** [comment]
> Can we modify the `writeForHash` or `ComputeAssetID` interface to panic instead?

We can do better, I reckon: we can tighten the contract of `writeForHash` to make errors impossible in the `ComputeAssetID` case. (Done.)

**Comment by jbowens** [comment]
lgtm

**Pull request merged**
