### PR TITLE
core: consolidate dashboard authz policy mapping

### PR DESCRIPTION
**Pull request by kr**
The policy map uses the same rules as the HTTP ServeMux
to match request paths, which means we can express what
we want for dashboard more succinctly: all dashboard
files are public.

### CODE REVIEW

**Comment by kr** [comment]
Also, given the matching rules, `/` is overly-permissive: it allows everything not explicitly mentioned in this table. We should default to deny for anything that's accidentally left out. For the specific case of allowing a request for exactly `/`, that is already done in a handler entirely outsize authz.

**Comment by kr** [comment]
PTAL

**Comment by jbowens** [comment]
> Also, given the matching rules, / is overly-permissive: it allows everything not explicitly mentioned in this table. We should default to deny for anything that's accidentally left out. For the specific case of allowing a request for exactly /, that is already done in a handler entirely outsize authz.

When I tested curling `/` locally with loopback_auth, I got:
```
{"code":"CH009","message":"Request could not be authenticated","temporary":false}
```
Is there something else we need to do to allow access to `/`?

**Comment by jeffomatic** [comment]
> Is there something else we need to do to allow access to /? /info and /dashboard still work as expected.

I've also noticed similar behavior accessing `/` outside of `loopback_auth`. It should redirect to `/dashboard` without authenticating.

**Comment by kr** [comment]
Ah, we moved the redirect outside of authz, but then it inadvertently got moved back inside again when authz moved out of chain/core in #1029. I'll undo the `/` part of this PR and we can fix the redirect separately.

**Comment by kr** [comment]
PTAL

This is what I get for trying to sneak something "small" in to an unrelated PR.

**Comment by jbowens** [comment]
lgtm

**Comment by kr** [comment]
😖

**Comment by kr** [comment]
rebased

**Pull request merged**
