### PR TITLE
core/account/utxodb: fix Reserve defer func

### PR DESCRIPTION
**Pull request by jbowens**
We don't define any PL/pgSQL `cancel_reservations` function, there's
only `cancel_reservation`. Also, rolling back is already covered by the
deferred SQL transaction rollback, so this call is redundant.

### CODE REVIEW

**Comment by jbowens** [comment]
PTAL

**Comment by bobg** [comment]
LGTM

Is it worth writing a plpgsql `cancel_reservations`? Perhaps not.

**Comment by jbowens** [comment]
Should I just get rid of the defer? It seems redundant with the defer rollback above.

**Comment by bobg** [comment]
> Should I just get rid of the defer? It seems redundant with the defer rollback above.

Oh, totally. Good call.

However, if an error occurs at a higher level in the callstack, it would be ideal to cancel any reservations then, which means returning a cancelable reservation object from this function. Not sure if it's really worth the effort, but certainly worth mentioning in a comment.

**Comment by bobg** [comment]
> which means returning a cancelable reservation object from this function

Oh we already do (the reservation ID).  Carry on...

**Pull request merged**
