### PR TITLE
vendor/github.com/lib/pq: update

### PR DESCRIPTION
**Pull request by tessr**
Updates lib/pq to `2704adc878c21e1329f46f6e56a1c387d788ff94`

### CODE REVIEW

**Comment by tessr** [comment]
ran it once 🔔  ptal

**Comment by kr** [comment]
Can you put the commit hash you used in the commit message?

**Comment by tessr** [comment]
I knew I was forgetting something.

**Comment by tessr** [comment]
Updated.

**Comment by kr** [comment]
LGTM

Does lib/pq include context support now? Future work should be to do https://github.com/chain/chain/blob/dd93e8d11193378a7c03f95d2dd870e6b35b5c96/database/sqlutil/logdriver.go#L68-L72

**Comment by tessr** [comment]
I'm not sure it does? https://github.com/lib/pq/search?utf8=%E2%9C%93&q=context&type=

**Pull request merged**
