### PR TITLE
dashboard: disable OS-autocomplete for all inputs

### PR DESCRIPTION
**Pull request by dominic**

### CODE REVIEW

**Comment by jeffomatic** [comment]
Looks good, although some people get real crazy when they do this, e.g.:

http://stackoverflow.com/questions/35513968/disable-auto-correct-in-safari-text-input

Is this the only attribute we need to add?

**Comment by jeffomatic** [comment]
Suspect most of these are mobile-related, but dunno if you had a chance to test out the solution with just `autocomplete`.

**Comment by dominic** [comment]
Hm - I went with the MDN recommendation: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

Let me double-check Safari

**Comment by dominic** [comment]
@jeffomatic Good call - Safari had some weirdness. Updated.

**Comment by jeffomatic** [comment]
I do notice an auto-capitalize option in the OSX keyboard options, so maybe we could to `autoCapitalize='off'` as well? We might be getting to the point where a `{...disableAutoText}` export would be handy.

**Comment by dominic** [comment]
@jeffomatic Updated again. I couldn't get any of my browsers to trigger autocapitalization (despite it being turned on in System Preferences) - might be a mobile-only option, but it also won't hurt anything.

**Pull request merged**
