### PR TITLE
core/signers: correctly record xpubs for a signer with multiple keys

### PR DESCRIPTION
**Pull request by bobg**
Avoid the Go pitfall involving reuse of loop variables.

### CODE REVIEW

**Comment by bobg** [comment]
PTAL

**Comment by kr** [comment]
LGTM

**Comment by jeffomatic** [comment]
Would it be possible to extend our Java integration tests to catch this case?

**Comment by dominic** [comment]
re @jeffomatic's comment, I'd call https://github.com/chain/chain/blob/main/sdk/java/src/test/java/com/chain/integration/TransactionTest.java#L177 an incomplete test of this use case. We should have a test that fails with less than the minimum number of signatures too.

**Pull request merged**
