### PR TITLE
core/txbuilder: add explicit retire action

### PR DESCRIPTION
**Pull request by jbowens**
Add an explicit retire action instead of using the `control_program`
action and specifying the OP_FAIL program. This provides more
flexibility as our implementation of retirement changes.

### CODE REVIEW

**Comment by jbowens** [comment]
Resurrecting this. @jeffomatic should I remove the SDK changes or should we just bump the SDK version when this goes out?

**Comment by jeffomatic** [comment]
1. By my understanding, this should be backward compatible with older SDKs, since the old `control_with_program` technique would still work, right?
2. We've added a Node SDK. @dominic or @chrisgarvin should be able to point you to the right spot.

**Comment by dominic** [comment]
re Node SDK: https://github.com/chain/chain/blob/main/sdk/node/src/api/transactions.js#L119-L131

Let's not modify Dashboard here? We'll be converting it to the new SDK this week, so it can be updated alongside that.

**Comment by jbowens** [comment]
> By my understanding, this should be backward compatible with older SDKs, since the old control_with_program technique would still work, right?

Yeah, just not newer SDKs with older coreds

**Comment by jeffomatic** [comment]
> Yeah, just not newer SDKs with older coreds

Okay cool, this would probably end up as a minor version bump--you're supposed to use the same major.minor version for the core and SDKs.

**Comment by erykwalder** [comment]
LGTM

**Pull request merged**
