### PR TITLE
core: respect page_size parameter in API endpoints that return pages

### PR DESCRIPTION
**Pull request by dominic**

### CODE REVIEW

**Comment by dominic** [comment]
PTAL

**Comment by jeffomatic** [comment]
1. Is this related to #346?
2. Is there any other specific issue that is unblocked by this change? It's a good change, but it's one that should probably be pushed out to all of our paginated endpoints.

**Comment by dominic** [comment]
This is unrelated to #346, where - in that case - the `page_size` param is handled correctly for access tokens, but the `after` object isn't generated correctly to request a new page. I discovered this issue while working on the Node SDK, but didn't want to bury the fix in the SDK pull request.

**Comment by dominic** [comment]
Digging deeper, I am seeing that many query endpoints also fail to respect this field, i.e. https://github.com/chain/chain/blob/main/core/query.go#L219

Should we extend this PR to include them all?

**Comment by jeffomatic** [comment]
> Should we extend this PR to include them all?

That sounds good--as we discussed IRL, the get-balances endpoint will be an exception. Please remember to also update the API spec YAML file as well...bug me if you need help with that.

**Comment by dominic** [comment]
@jeffomatic PTAL again

**Comment by dominic** [comment]
@jeffomatic updated

**Pull request merged**
