### PR TITLE
cmd/cored: rename loopback_auth to localhost_auth

### PR DESCRIPTION
**Pull request by kr**

### CODE REVIEW

**Comment by kr** [comment]
PTAL

**Comment by kr** [comment]
Prob needs dashboard updates? And other updates?

**Comment by kr** [comment]
Or not! We already updated the "feature name" in a previous PR.

**Comment by tessr** [comment]
The windows installer readme needs updating too!

**Comment by kr** [comment]
I think the windows installer was already updated before! It says "localhost_auth"

**Comment by tessr** [comment]
...the readme definitely says "loopback_auth," unless I'm blind

**Comment by tessr** [comment]
now that my eyesight has returned, LGTM

**Pull request merged**
