### PR TITLE
dashboard: remove interim API library

### PR DESCRIPTION
**Pull request by dominic**
Dashboard now uses the official Chain Node.js SDK

### CODE REVIEW

**Comment by jeffomatic** [comment]
Will be posting screenshots of things I notice as I QA this branch.

**Comment by jeffomatic** [comment]
Account/asset keys are not displayed correctly

screen shot 2017-02-15 at 6 00 35 pm

**Comment by jeffomatic** [comment]
Some transaction details are appearing as null

screen shot 2017-02-15 at 6 03 19 pm

**Comment by jeffomatic** [comment]
tx inputs have a "control program" field, which seems incorrect

**Comment by jeffomatic** [comment]
Outputs in tx display have transaction ID, which is redundant, and the values are null

screen shot 2017-02-15 at 6 08 12 pm

**Comment by jeffomatic** [comment]
Client token and network token links are broken

**Comment by jeffomatic** [comment]
After clicking Core Status: Delete All Data, the subsequent Core Config page flickers

**Comment by jeffomatic** [comment]
Error due to not selecting a pre-existing HSM key is a little unclear about the cause

screen shot 2017-02-15 at 6 22 58 pm

**Comment by jeffomatic** [comment]
Resetting core does not delete MockHSM keys

**Comment by jeffomatic** [comment]
Some outputs have null as output ID. This was the result of spending an unspent output and retiring it. Unsure if tx structure is related.

screen shot 2017-02-15 at 6 33 47 pm

**Comment by dominic** [comment]
> Error due to not selecting a pre-existing HSM key is a little unclear about the cause

That's on main too - we should extract that into an isssue.

**Comment by jeffomatic** [comment]
pagination doesn't work, still uses `context`

**Pull request merged**
