### PR TITLE
protocol/bc: replace AssetID with a protobuf type

### PR DESCRIPTION
**Pull request by bobg**
The protobuf definition of `AssetID` is identical to that of `Hash`, allowing conversion between the two. `AssetID` gets much of its behavior from conversion to the `Hash` type. (See the discussion in https://github.com/chain/chain/pull/850.)

### CODE REVIEW

**Comment by bobg** [comment]
PTAL

**Comment by bobg** [comment]
PTAL

**Comment by kr** [comment]
:eyes:

**Comment by kr** [comment]
Need to `git rm hash.proto`? Otherwise LGTM

**Pull request merged**
