### PR TITLE
sync/idempotency: new package

### PR DESCRIPTION
**Pull request by jbowens**
Add new package of a slightly modified version of groupcache's
`singleflight` package ([already vendored](https://github.com/chain/chain/tree/main/vendor/github.com/golang/groupcache/singleflight)). This package provides
duplicate call suppression until a key is explicitly forgotten.

This will be used as part of the in-memory account UTXO reserver.

### CODE REVIEW

**Comment by jbowens** [comment]
PTAL

**Comment by kr** [comment]
:eyes:

**Comment by danrobinson** [comment]
If there are changes to the code, can we tweak the license header like what's done in the `vet` code and add something to the top-level NOTICE file? I'm happy to do this myself by tomorrow.

**Comment by jbowens** [comment]
> If there are changes to the code, can we tweak the license header like what's done in the vet code and add something to the top-level NOTICE file? I'm happy to do this myself by tomorrow.

Sure, whatever's required. There are a couple really small changes to the code.

**Comment by danrobinson** [comment]
Moved the license NOTICE to conform with how we did the others. Now LGTM

**Pull request merged**
