### PR TITLE
vendor: add raft dependencies

### PR DESCRIPTION
**Pull request by tessr**
This commit adds dependencies for our raft package, updates the vendored coreos/etcd package, adds _its_ dependencies to our vendor directory, and removes its Godep directory. (That package has stopped using godep since we last updated it.)

Vendored from:
github.com/ugorji/go/codec: f1f1a805ed361a0e078bb537e4ea78cd37dcf065
github.com/coreos/go-semver: 5e3acbb5668c4c3deb4842615c4098eb61fb6b1e
github.com/coreos/etcd: 47cb8a012ad0ddd8505bb573066ca1d27b1c46c3

### CODE REVIEW

**Comment by jbowens** [comment]
🤸‍♂️

**Comment by kr** [comment]
Can you put the commit hash and repo url of where these dependencies came from in the commit message?

**Comment by tessr** [comment]
Yes.

**Comment by kr** [comment]
Thank u!

**Comment by tessr** [comment]
Anyone want to look over this again? It's changed a bunch since Jackson ~~enabled my wanton dependency updates~~ reviewed it.

**Comment by kr** [comment]
LGTM

**Pull request merged**
