### PR TITLE
core/migrate: remove not null constraint from txfeeds client_token

### LINKED ISSUE #145: /create-transaction-feed returns 500 error on null client_token param
Sending a null or undefined `client_token` param to the `/create-transaction-feed` endpoint will yield the following:

```
app=cored ... at=http.go:51 t=2016-11-02T23:07:29.398290512Z
status=500 chaincode=CH000 path=/create-transaction-feed
error="pq: null value in column \"client_token\" violates not-null constraint"
```

This is the client's problem, not the server's, so `CH000` isn't quite right here. The endpoint should either tolerate a blank idempotency token (recommended), or return a 400-class error.

### PR DESCRIPTION
**Pull request by tessr**
Resolves #145.

### CODE REVIEW

**Comment by tessr** [comment]
PTAL

**Comment by jeffomatic** [comment]
Do we still dump the full schema?

**Comment by jbowens** [comment]
yeah, we do `bin/dumpschema`

**Comment by tessr** [comment]
This brave new golang migration world is too much for me.

**Comment by tessr** [comment]
P

**Comment by tessr** [comment]
PTAL

**Comment by jeffomatic** [comment]
LGTM

**Pull request merged**
