### PR TITLE
cmd/md2html: multi-language code snippets

### PR DESCRIPTION
**Pull request by jeffomatic**
This commit adds multi-language snippet support to md2html. Documents should provide snippet directives with the following structure:

    $code <snippet-name> <file1> <file2> ...

Example:

    $code create-client ../examples/java/FiveMinuteGuide.java ../examples/ruby/five_minute_guide.rb

A snippet block will be generated for every named file. The file must contain the specified snippet, or a block of error text will be generated instead.

In the browser, snippets for different languages will be displayed based on the currently-selected language.

### CODE REVIEW

**Comment by jeffomatic** [comment]
lang-select

**Comment by jeffomatic** [comment]
PTAL

**Comment by dominic** [comment]
:eye::eye:

**Comment by dominic** [comment]
LGTM

**Pull request merged**
