### PR TITLE
vendor/github.com/lsegal/gucumber: update

### PR DESCRIPTION
**Pull request by tessr**
Updates `github.com/lsegal/gucumber` to `71608e2f6e76fd4da5b09a376aeec7a5c0b5edbc`. This is a dependency used by the aws packages.

### CODE REVIEW

**Comment by kr** [comment]
I think it may no longer be a dependency used by the aws packages! Their docs claim they vendor all their dependencies, and there is a vendor directory inside aws-sdk-go, and it doesn't contain gucumber :shruggie:

**Comment by tessr** [comment]
Ah, does this mean we can delete all the packages we've vendored just for AWS?

**Comment by kr** [comment]
> Ah, does this mean we can delete all the packages we've vendored just for AWS?

Yeah, pretty sure.

**Comment by tessr** [comment]
Awesome! I had made a list of them for _just this very purpose_

**Pull request closed without merging**
