### PR TITLE
core/query: leave unmarshaling to request layer

### PR DESCRIPTION
**Pull request by erykwalder**
Rather than unmarshaling from the database into a struct or map
and then doing conversion at the request layer before sending a
response to the client, just leave the unmarshaling to the request
layer, where it can guarantee ordering.

### CODE REVIEW

**Comment by kr** [comment]
:eyes:

**Comment by jbowens** [comment]
somewhat related, what do you think about replacing the `map[string]interface{}` bag of props with explicit structs for annotated objects, like `query.AnnotatedTx`, `query.AnnotatedInput`, etc.

I started trying it out on a wip branch, because I think it would make the work to remove jsonb easier.

**Comment by erykwalder** [comment]
Would the query package know all of the potential annotations that an object would receive?

**Comment by jbowens** [comment]
> Would the query package know all of the potential annotations that an object would receive?

Yeah, it would need to anyways if we're going to convert the tables from jsonb to tables with schemas.

**Comment by kr** [comment]
LGTM

My only feedback is I found it difficult to get my bearings just from the description above. Maybe being just a bit more explicit would be nice, like:

> Rather than unmarshaling from the database into a struct or map
and then doing conversion at the request layer before sending a
response to the client, just leave the unmarshaling to the request
layer, where it can guarantee ordering.

**Pull request merged**
