### PR TITLE
dashboard: input autocomplete suggestions trigger on first keydown

### PR DESCRIPTION
**Pull request by chrisgarvin**

### CODE REVIEW

**Comment by chrisgarvin** [comment]
Fixes issue where autocomplete suggestions would not trigger on first keydown upon entering page.

Original:
image

Modified:
image

**Comment by chrisgarvin** [comment]
PTAL

**Comment by dominic** [comment]
One comment - can you remove the `cb` parameter from the `fetchAll` definition at https://github.com/chain/chain/blob/d6b12a02797e86e8286d0dd51f76a5ea6fedf40d/dashboard/src/components/Common/Autocomplete/AutocompleteField.jsx#L92 ? It's not used anymore, and it turns out `fetchAll` doesn't call it in its current implementation.

**Comment by chrisgarvin** [comment]
@dominic removed cb from fetchAll 👍

**Comment by dominic** [comment]
LGTM

**Pull request merged**
