### PR TITLE
Codeowners: add file

### PR DESCRIPTION
**Pull request by dominic**
Experimenting with GitHub's new automatic reviewer assignment
system, and potentially using it for branch protection.

### CODE REVIEW

**Comment by kr** [comment]
Minor request, can we steer clear of the ALL CAPS file names? It's needlessly ostentatious.

**Comment by kr** [comment]
If this is consistent with the other GitHub special files, their file name matching is not case sensitive.

**Comment by dominic** [comment]
Good to know; will update.

**Comment by kr** [comment]
We could call it `codeowners` or, if for some reason we want it to show up near the top of `ls` output (but why?) then we can capitalize it as `Codeowners`.

**Comment by kr** [comment]
LGTM

**Pull request merged**
