### PR TITLE
docs: add development instructions to readme

### PR DESCRIPTION
**Pull request by dominic**

### CODE REVIEW

**Comment by dominic** [comment]
PTAL

**Comment by oleganza** [comment]
@dominic WDYT of having this, friendlier command to run from $CHAIN:

    $ go run ./cmd/md2html/*.go

**Comment by ryandotsmith** [comment]
@dominic do we need the TOC in the readme?
Also, it would be helpful to also describe how we deploy documentation. Imagine a case where someone would like to change the docs. What are the exact steps required to get them deploy to chain.com/docs and optionally included in cored.

**Comment by kr** [comment]
Please avoid using 'go run' with a list of .go files for stable tools like this. It's slow and fragile (it doesn't respect build constraints, so if we ever have to add a build tag or platform-specific code, it'll break).

It's much better to `go install chain/cmd/md2html` so you get a true Unix command, and from then on run the command.

**Comment by dominic** [comment]
@kr :+1: I think that should def be our policy for all READMEs then

**Comment by kr** [comment]
Ok. Oh also I just caught up on some of the slack history. If it's common to be editing md2html along with the docs, then sure 'go run' can be more convenient than 'go install && md2html', but in that case I think it deserves to be called out in the readme why we suggest doing that. Because it's the exception rather than the rule.

**Comment by dominic** [comment]
PTAL again @ryandotsmith @kr

**Pull request merged**
