### PR TITLE
errors: clarify documentation

### PR DESCRIPTION
**Pull request by kr**
Using these parameter names for Sub seems to make its
behavior clearer.

### CODE REVIEW

**Comment by kr** [comment]
PTAL

This also addresses the potential syntax highlighting problem raised in https://github.com/chain/chain/pull/496#discussion_r100225050.

**Comment by bobg** [comment]
Actually, `root` sounds like it's going to be the more deeply buried error. How about `newRoot` and `orig`? :bike: :house:

**Comment by kr** [comment]
Let me try to adjust the wording to hopefully make it clearer. (I already wasn't super happy with the existing wording.)

**Comment by kr** [comment]
Ok, updated. There is no "new" and "old" involved. It is just a root from one place and everything else from another place.

**Comment by bobg** [comment]
LGTM

**Pull request merged**
