### PR TITLE
ReleaseNotes.md: remove stale document

### PR DESCRIPTION
**Pull request by jeffomatic**

### CODE REVIEW

**Comment by jeffomatic** [comment]
PTAL

**Comment by kr** [comment]
LGTM

**Comment by dominic** [comment]
Just found this old conversation FYI

screen shot 2017-02-24 at 10 37 41 am

**Comment by jeffomatic** [comment]
Thanks @dominic . I think the inspiration was good but it hasn't proven out, and may end up being confusing next to the changelog. We can of course revisit in the future.

**Pull request merged**
