### PR TITLE
core: add grant API stubs

### PR DESCRIPTION
**Pull request by dominic**

### CODE REVIEW

**Comment by tessr** [comment]
I am going to rebase `acl-core` over `main` to pick up the authn changes, and then we can merge this in, if that sg?

**Comment by dominic** [comment]
:+1: sounds great - thanks!

**Comment by tessr** [comment]
I've done the rebase over main, now! (Sorry, it looks like it made things a bit messy.) 

Anyways, feel free to rebase again and I think that will tidy this up? And then we can merge it in.

**Comment by tessr** [comment]
Actually, I had intentionally dropped a couple of commits when rebasing over main; maybe you should `rebase -i` and drop my commits and then rebase your own commits over `acl-core`? Sorry for the mess 😞

**Comment by dominic** [comment]
@tessr Cool - nbd. Let me do that now.

**Comment by tessr** [comment]
Seems fine to me!

**Comment by tessr** [comment]
(Wercker is failing because I commit recklessly and I messed something up)

**Pull request merged**
