### PR TITLE
protocol/bc: remove indirection from entry protos

### PR DESCRIPTION
**Pull request by jbowens**
Remove the Body and Witness contained proto messages, moving
those fields onto the parent entry proto. This was motivated by #983
because it will prevent a lot of nil checks.

### CODE REVIEW

**Comment by jbowens** [comment]
PTAL

**Comment by kr** [comment]
:eyes:

**Comment by kr** [comment]
It's too bad all the writeForHash functions have to reiterate all the fields, but I suppose it's better than all those nil checks.

LGTM

**Comment by bobg** [comment]
Another reason to be unthrilled about protobufs. :disappointed:

**Pull request merged**
