### PR TITLE
core: create new policy crosscore-signblock

### PR DESCRIPTION
**Pull request by tessr**
This creates a new policy `crosscore-signblock`. Users can manually make the grants and specify what guards are associated with this policy.

### CODE REVIEW

**Comment by tessr** [comment]
PTAL

**Comment by kr** [comment]
:eyes:

**Comment by kr** [comment]
LGTM

**Comment by jeffomatic** [comment]
Whoops, would be good to add a test for this policy in `core/authz_test.go`.

**Comment by tessr** [comment]
There is one: https://github.com/chain/chain/pull/1063/files#diff-b019f310c8d023cbf67dac1011c185d9R120

**Comment by jeffomatic** [comment]
@tessr Ah double-whoops, sorry!

**Comment by tessr** [comment]
It got swallowed in all the line-length changes :)

**Pull request merged**
